INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (100, 'King', 288000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (101, 'Kochhar', 204000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (102, 'De Haan', 204000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (103, 'Hunold', 108000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (104, 'Ernst', 72000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (105, 'Austin', 57600.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (106, 'Pataballa', 57600.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (107, 'Lorentz', 50400.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (108, 'Greenberg', 144000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (109, 'Faviet', 108000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (110, 'Chen', 98400.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (111, 'Sciarra', 92400.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (112, 'Urman', 93600.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (113, 'Popp', 82800.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (114, 'Raphaely', 132000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (115, 'Khoo', 37200.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (116, 'Baida', 34800.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (117, 'Tobias', 33600.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (118, 'Himuro', 31200.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (119, 'Colmenares', 30000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (120, 'Weiss', 96000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (121, 'Fripp', 98400.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (122, 'Kaufling', 94800.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (123, 'Vollman', 78000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (124, 'Mourgos', 69600.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (125, 'Nayer', 38400.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (126, 'Mikkilineni', 32400.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (127, 'Landry', 28800.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (128, 'Markle', 26400.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (129, 'Bissot', 39600.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (130, 'Atkinson', 33600.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (131, 'Marlow', 30000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (132, 'Olson', 25200.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (133, 'Mallin', 39600.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (134, 'Rogers', 34800.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (135, 'Gee', 28800.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (136, 'Philtanker', 26400.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (137, 'Ladwig', 43200.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (138, 'Stiles', 38400.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (139, 'Seo', 32400.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (140, 'Patel', 30000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (141, 'Rajs', 42000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (142, 'Davies', 37200.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (143, 'Matos', 31200.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (144, 'Vargas', 30000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (145, 'Russell', 168000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (146, 'Partners', 162000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (147, 'Errazuriz', 144000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (148, 'Cambrault', 132000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (149, 'Zlotkey', 126000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (150, 'Tucker', 120000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (151, 'Bernstein', 114000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (152, 'Hall', 108000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (153, 'Olsen', 96000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (154, 'Cambrault', 90000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (155, 'Tuvault', 84000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (156, 'King', 120000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (157, 'Sully', 114000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (158, 'McEwen', 108000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (159, 'Smith', 96000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (160, 'Doran', 90000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (161, 'Sewall', 84000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (162, 'Vishney', 126000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (163, 'Greene', 114000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (164, 'Marvins', 86400.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (165, 'Lee', 81600.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (166, 'Ande', 76800.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (167, 'Banda', 74400.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (168, 'Ozer', 138000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (169, 'Bloom', 120000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (170, 'Fox', 115200.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (171, 'Smith', 88800.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (172, 'Bates', 87600.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (173, 'Kumar', 73200.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (174, 'Abel', 132000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (175, 'Hutton', 105600.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (176, 'Taylor', 103200.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (177, 'Livingston', 100800.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (178, 'Grant', 84000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (179, 'Johnson', 74400.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (180, 'Taylor', 38400.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (181, 'Fleaur', 37200.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (182, 'Sullivan', 30000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (183, 'Geoni', 33600.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (184, 'Sarchand', 50400.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (185, 'Bull', 49200.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (186, 'Dellinger', 40800.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (187, 'Cabrio', 36000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (188, 'Chung', 45600.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (189, 'Dilly', 43200.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (190, 'Gates', 34800.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (191, 'Perkins', 30000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (192, 'Bell', 48000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (193, 'Everett', 46800.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (194, 'McCain', 38400.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (195, 'Jones', 33600.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (196, 'Walsh', 37200.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (197, 'Feeney', 36000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (198, 'OConnell', 31200.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (199, 'Grant', 31200.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (200, 'Whalen', 52800.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (201, 'Hartstein', 156000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (202, 'Fay', 72000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (203, 'Mavris', 78000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (204, 'Baer', 120000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (205, 'Higgins', 144000.00);
INSERT INTO `运算符` (`employee_id`, `last_name`, `年薪`) VALUES (206, 'Gietz', 99600.00);
INSERT INTO `运算符` (`'100' + 50`) VALUES (150);
INSERT INTO `运算符` (`last_name + 100`) VALUES (100);
INSERT INTO `运算符` (`last_name + 100`) VALUES (100);
INSERT INTO `运算符` (`last_name + 100`) VALUES (100);
INSERT INTO `运算符` (`last_name + 100`) VALUES (100);
INSERT INTO `运算符` (`last_name + 100`) VALUES (100);
INSERT INTO `运算符` (`last_name`) VALUES ('Partners');
INSERT INTO `运算符` (`last_name`) VALUES ('Errazuriz');
INSERT INTO `运算符` (`last_name`) VALUES ('Cambrault');
INSERT INTO `运算符` (`last_name`) VALUES ('Tucker');
INSERT INTO `运算符` (`last_name`) VALUES ('Smith');
INSERT INTO `运算符` (`last_name`) VALUES ('Doran');
INSERT INTO `运算符` (`last_name`) VALUES ('Abel');
INSERT INTO `运算符` (`last_name`) VALUES ('Partners');
INSERT INTO `运算符` (`last_name`) VALUES ('Errazuriz');
INSERT INTO `运算符` (`last_name`) VALUES ('Cambrault');
INSERT INTO `运算符` (`last_name`) VALUES ('Tucker');
INSERT INTO `运算符` (`last_name`) VALUES ('Smith');
INSERT INTO `运算符` (`last_name`) VALUES ('Doran');
INSERT INTO `运算符` (`last_name`) VALUES ('Abel');
INSERT INTO `运算符` (`last_name`) VALUES ('King');
INSERT INTO `运算符` (`last_name`) VALUES ('Kochhar');
INSERT INTO `运算符` (`last_name`) VALUES ('De Haan');
INSERT INTO `运算符` (`last_name`) VALUES ('Hunold');
INSERT INTO `运算符` (`last_name`) VALUES ('Ernst');
INSERT INTO `运算符` (`last_name`) VALUES ('Austin');
INSERT INTO `运算符` (`last_name`) VALUES ('Pataballa');
INSERT INTO `运算符` (`last_name`) VALUES ('Lorentz');
INSERT INTO `运算符` (`last_name`) VALUES ('Greenberg');
INSERT INTO `运算符` (`last_name`) VALUES ('Faviet');
INSERT INTO `运算符` (`last_name`) VALUES ('Chen');
INSERT INTO `运算符` (`last_name`) VALUES ('Sciarra');
INSERT INTO `运算符` (`last_name`) VALUES ('Urman');
INSERT INTO `运算符` (`last_name`) VALUES ('Popp');
INSERT INTO `运算符` (`last_name`) VALUES ('Raphaely');
INSERT INTO `运算符` (`last_name`) VALUES ('Khoo');
INSERT INTO `运算符` (`last_name`) VALUES ('Baida');
INSERT INTO `运算符` (`last_name`) VALUES ('Tobias');
INSERT INTO `运算符` (`last_name`) VALUES ('Himuro');
INSERT INTO `运算符` (`last_name`) VALUES ('Colmenares');
INSERT INTO `运算符` (`last_name`) VALUES ('Weiss');
INSERT INTO `运算符` (`last_name`) VALUES ('Fripp');
INSERT INTO `运算符` (`last_name`) VALUES ('Kaufling');
INSERT INTO `运算符` (`last_name`) VALUES ('Vollman');
INSERT INTO `运算符` (`last_name`) VALUES ('Mourgos');
INSERT INTO `运算符` (`last_name`) VALUES ('Nayer');
INSERT INTO `运算符` (`last_name`) VALUES ('Mikkilineni');
INSERT INTO `运算符` (`last_name`) VALUES ('Landry');
INSERT INTO `运算符` (`last_name`) VALUES ('Markle');
INSERT INTO `运算符` (`last_name`) VALUES ('Bissot');
INSERT INTO `运算符` (`last_name`) VALUES ('Atkinson');
INSERT INTO `运算符` (`last_name`) VALUES ('Marlow');
INSERT INTO `运算符` (`last_name`) VALUES ('Olson');
INSERT INTO `运算符` (`last_name`) VALUES ('Mallin');
INSERT INTO `运算符` (`last_name`) VALUES ('Rogers');
INSERT INTO `运算符` (`last_name`) VALUES ('Gee');
INSERT INTO `运算符` (`last_name`) VALUES ('Philtanker');
INSERT INTO `运算符` (`last_name`) VALUES ('Ladwig');
INSERT INTO `运算符` (`last_name`) VALUES ('Stiles');
INSERT INTO `运算符` (`last_name`) VALUES ('Seo');
INSERT INTO `运算符` (`last_name`) VALUES ('Patel');
INSERT INTO `运算符` (`last_name`) VALUES ('Rajs');
INSERT INTO `运算符` (`last_name`) VALUES ('Davies');
INSERT INTO `运算符` (`last_name`) VALUES ('Matos');
INSERT INTO `运算符` (`last_name`) VALUES ('Vargas');
INSERT INTO `运算符` (`last_name`) VALUES ('Taylor');
INSERT INTO `运算符` (`last_name`) VALUES ('Fleaur');
INSERT INTO `运算符` (`last_name`) VALUES ('Sullivan');
INSERT INTO `运算符` (`last_name`) VALUES ('Geoni');
INSERT INTO `运算符` (`last_name`) VALUES ('Sarchand');
INSERT INTO `运算符` (`last_name`) VALUES ('Bull');
INSERT INTO `运算符` (`last_name`) VALUES ('Dellinger');
INSERT INTO `运算符` (`last_name`) VALUES ('Cabrio');
INSERT INTO `运算符` (`last_name`) VALUES ('Chung');
INSERT INTO `运算符` (`last_name`) VALUES ('Dilly');
INSERT INTO `运算符` (`last_name`) VALUES ('Gates');
INSERT INTO `运算符` (`last_name`) VALUES ('Perkins');
INSERT INTO `运算符` (`last_name`) VALUES ('Bell');
INSERT INTO `运算符` (`last_name`) VALUES ('Everett');
INSERT INTO `运算符` (`last_name`) VALUES ('McCain');
INSERT INTO `运算符` (`last_name`) VALUES ('Jones');
INSERT INTO `运算符` (`last_name`) VALUES ('Walsh');
INSERT INTO `运算符` (`last_name`) VALUES ('Feeney');
INSERT INTO `运算符` (`last_name`) VALUES ('OConnell');
INSERT INTO `运算符` (`last_name`) VALUES ('Grant');
INSERT INTO `运算符` (`last_name`) VALUES ('Whalen');
INSERT INTO `运算符` (`last_name`) VALUES ('Hartstein');
INSERT INTO `运算符` (`last_name`) VALUES ('Fay');
INSERT INTO `运算符` (`last_name`) VALUES ('Mavris');
INSERT INTO `运算符` (`last_name`) VALUES ('Baer');
INSERT INTO `运算符` (`last_name`) VALUES ('Higgins');
INSERT INTO `运算符` (`last_name`) VALUES ('Gietz');
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('King', 24000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Kochhar', 17000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('De Haan', 17000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Hunold', 9000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Ernst', 6000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Austin', 4800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Pataballa', 4800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Lorentz', 4200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Greenberg', 12000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Faviet', 9000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Chen', 8200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Sciarra', 7700.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Urman', 7800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Popp', 6900.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Raphaely', 11000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Khoo', 3100.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Baida', 2900.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Tobias', 2800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Himuro', 2600.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Colmenares', 2500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Weiss', 8000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Fripp', 8200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Kaufling', 7900.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Vollman', 6500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Mourgos', 5800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Nayer', 3200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Mikkilineni', 2700.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Landry', 2400.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Markle', 2200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Bissot', 3300.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Atkinson', 2800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Marlow', 2500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Olson', 2100.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Mallin', 3300.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Rogers', 2900.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Gee', 2400.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Philtanker', 2200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Ladwig', 3600.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Stiles', 3200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Seo', 2700.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Patel', 2500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Rajs', 3500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Davies', 3100.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Matos', 2600.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Vargas', 2500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Taylor', 3200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Fleaur', 3100.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Sullivan', 2500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Geoni', 2800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Sarchand', 4200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Bull', 4100.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Dellinger', 3400.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Cabrio', 3000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Chung', 3800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Dilly', 3600.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Gates', 2900.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Perkins', 2500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Bell', 4000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Everett', 3900.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('McCain', 3200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Jones', 2800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Walsh', 3100.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Feeney', 3000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('OConnell', 2600.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Grant', 2600.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Whalen', 4400.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Hartstein', 13000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Fay', 6000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Mavris', 6500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Baer', 10000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Higgins', 12000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Gietz', 8300.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('King', 24000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Kochhar', 17000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('De Haan', 17000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Hunold', 9000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Ernst', 6000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Austin', 4800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Pataballa', 4800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Lorentz', 4200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Greenberg', 12000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Faviet', 9000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Chen', 8200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Sciarra', 7700.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Urman', 7800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Popp', 6900.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Raphaely', 11000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Khoo', 3100.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Baida', 2900.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Tobias', 2800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Himuro', 2600.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Colmenares', 2500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Weiss', 8000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Fripp', 8200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Kaufling', 7900.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Vollman', 6500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Mourgos', 5800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Nayer', 3200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Mikkilineni', 2700.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Landry', 2400.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Markle', 2200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Bissot', 3300.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Atkinson', 2800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Marlow', 2500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Olson', 2100.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Mallin', 3300.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Rogers', 2900.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Gee', 2400.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Philtanker', 2200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Ladwig', 3600.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Stiles', 3200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Seo', 2700.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Patel', 2500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Rajs', 3500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Davies', 3100.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Matos', 2600.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Vargas', 2500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Taylor', 3200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Fleaur', 3100.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Sullivan', 2500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Geoni', 2800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Sarchand', 4200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Bull', 4100.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Dellinger', 3400.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Cabrio', 3000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Chung', 3800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Dilly', 3600.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Gates', 2900.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Perkins', 2500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Bell', 4000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Everett', 3900.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('McCain', 3200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Jones', 2800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Walsh', 3100.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Feeney', 3000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('OConnell', 2600.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Grant', 2600.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Whalen', 4400.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Hartstein', 13000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Fay', 6000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Mavris', 6500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Baer', 10000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Higgins', 12000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Gietz', 8300.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('King', 24000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Kochhar', 17000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('De Haan', 17000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Hunold', 9000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Ernst', 6000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Austin', 4800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Pataballa', 4800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Lorentz', 4200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Greenberg', 12000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Faviet', 9000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Chen', 8200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Sciarra', 7700.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Urman', 7800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Popp', 6900.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Raphaely', 11000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Khoo', 3100.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Baida', 2900.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Tobias', 2800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Himuro', 2600.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Colmenares', 2500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Weiss', 8000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Fripp', 8200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Kaufling', 7900.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Vollman', 6500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Mourgos', 5800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Nayer', 3200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Mikkilineni', 2700.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Landry', 2400.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Markle', 2200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Bissot', 3300.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Atkinson', 2800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Marlow', 2500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Olson', 2100.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Mallin', 3300.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Rogers', 2900.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Gee', 2400.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Philtanker', 2200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Ladwig', 3600.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Stiles', 3200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Seo', 2700.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Patel', 2500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Rajs', 3500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Davies', 3100.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Matos', 2600.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Vargas', 2500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Taylor', 3200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Fleaur', 3100.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Sullivan', 2500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Geoni', 2800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Sarchand', 4200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Bull', 4100.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Dellinger', 3400.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Cabrio', 3000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Chung', 3800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Dilly', 3600.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Gates', 2900.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Perkins', 2500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Bell', 4000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Everett', 3900.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('McCain', 3200.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Jones', 2800.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Walsh', 3100.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Feeney', 3000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('OConnell', 2600.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Grant', 2600.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Whalen', 4400.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Hartstein', 13000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Fay', 6000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Mavris', 6500.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Baer', 10000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Higgins', 12000.00);
INSERT INTO `运算符` (`last_name`, `salary`) VALUES ('Gietz', 8300.00);
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Hunold', 9000.00, 'IT_PROG');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Greenberg', 12000.00, 'FI_MGR');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Faviet', 9000.00, 'FI_ACCOUNT');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Chen', 8200.00, 'FI_ACCOUNT');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Raphaely', 11000.00, 'PU_MAN');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Weiss', 8000.00, 'ST_MAN');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Fripp', 8200.00, 'ST_MAN');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Errazuriz', 12000.00, 'SA_MAN');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Cambrault', 11000.00, 'SA_MAN');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Zlotkey', 10500.00, 'SA_MAN');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Tucker', 10000.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Bernstein', 9500.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Hall', 9000.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Olsen', 8000.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('King', 10000.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Sully', 9500.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('McEwen', 9000.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Smith', 8000.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Vishney', 10500.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Greene', 9500.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Ozer', 11500.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Bloom', 10000.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Fox', 9600.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Abel', 11000.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Hutton', 8800.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Taylor', 8600.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Livingston', 8400.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Baer', 10000.00, 'PR_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Higgins', 12000.00, 'AC_MGR');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Gietz', 8300.00, 'AC_ACCOUNT');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('King', 24000.00, 'AD_PRES');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Kochhar', 17000.00, 'AD_VP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('De Haan', 17000.00, 'AD_VP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Ernst', 6000.00, 'IT_PROG');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Austin', 4800.00, 'IT_PROG');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Pataballa', 4800.00, 'IT_PROG');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Lorentz', 4200.00, 'IT_PROG');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Chen', 8200.00, 'FI_ACCOUNT');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Sciarra', 7700.00, 'FI_ACCOUNT');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Urman', 7800.00, 'FI_ACCOUNT');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Popp', 6900.00, 'FI_ACCOUNT');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Khoo', 3100.00, 'PU_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Baida', 2900.00, 'PU_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Tobias', 2800.00, 'PU_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Himuro', 2600.00, 'PU_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Colmenares', 2500.00, 'PU_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Weiss', 8000.00, 'ST_MAN');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Fripp', 8200.00, 'ST_MAN');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Kaufling', 7900.00, 'ST_MAN');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Vollman', 6500.00, 'ST_MAN');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Mourgos', 5800.00, 'ST_MAN');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Nayer', 3200.00, 'ST_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Mikkilineni', 2700.00, 'ST_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Landry', 2400.00, 'ST_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Markle', 2200.00, 'ST_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Bissot', 3300.00, 'ST_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Atkinson', 2800.00, 'ST_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Marlow', 2500.00, 'ST_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Olson', 2100.00, 'ST_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Mallin', 3300.00, 'ST_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Rogers', 2900.00, 'ST_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Gee', 2400.00, 'ST_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Philtanker', 2200.00, 'ST_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Ladwig', 3600.00, 'ST_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Stiles', 3200.00, 'ST_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Seo', 2700.00, 'ST_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Patel', 2500.00, 'ST_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Rajs', 3500.00, 'ST_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Davies', 3100.00, 'ST_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Matos', 2600.00, 'ST_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Vargas', 2500.00, 'ST_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Russell', 14000.00, 'SA_MAN');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Partners', 13500.00, 'SA_MAN');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Olsen', 8000.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Cambrault', 7500.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Tuvault', 7000.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Smith', 8000.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Doran', 7500.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Sewall', 7000.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Marvins', 7200.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Lee', 6800.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Ande', 6400.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Banda', 6200.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Smith', 7400.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Bates', 7300.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Kumar', 6100.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Hutton', 8800.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Taylor', 8600.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Livingston', 8400.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Grant', 7000.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Johnson', 6200.00, 'SA_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Taylor', 3200.00, 'SH_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Fleaur', 3100.00, 'SH_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Sullivan', 2500.00, 'SH_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Geoni', 2800.00, 'SH_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Sarchand', 4200.00, 'SH_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Bull', 4100.00, 'SH_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Dellinger', 3400.00, 'SH_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Cabrio', 3000.00, 'SH_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Chung', 3800.00, 'SH_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Dilly', 3600.00, 'SH_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Gates', 2900.00, 'SH_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Perkins', 2500.00, 'SH_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Bell', 4000.00, 'SH_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Everett', 3900.00, 'SH_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('McCain', 3200.00, 'SH_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Jones', 2800.00, 'SH_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Walsh', 3100.00, 'SH_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Feeney', 3000.00, 'SH_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('OConnell', 2600.00, 'SH_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Grant', 2600.00, 'SH_CLERK');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Whalen', 4400.00, 'AD_ASST');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Hartstein', 13000.00, 'MK_MAN');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Fay', 6000.00, 'MK_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Mavris', 6500.00, 'HR_REP');
INSERT INTO `运算符` (`last_name`, `salary`, `job_id`) VALUES ('Gietz', 8300.00, 'AC_ACCOUNT');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Hunold', 'IT_PROG');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Ernst', 'IT_PROG');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Austin', 'IT_PROG');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Pataballa', 'IT_PROG');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Lorentz', 'IT_PROG');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Tucker', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Bernstein', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Hall', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Olsen', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Cambrault', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Tuvault', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('King', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Sully', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('McEwen', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Smith', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Doran', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Sewall', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Vishney', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Greene', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Marvins', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Lee', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Ande', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Banda', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Ozer', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Bloom', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Fox', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Smith', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Bates', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Kumar', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Abel', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Hutton', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Taylor', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Livingston', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Grant', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`) VALUES ('Johnson', 'SA_REP');
INSERT INTO `运算符` (`last_name`, `job_id`, `department_id`) VALUES ('Whalen', 'AD_ASST', 10);
INSERT INTO `运算符` (`last_name`, `job_id`, `department_id`) VALUES ('Hartstein', 'MK_MAN', 20);
INSERT INTO `运算符` (`last_name`, `job_id`, `department_id`) VALUES ('Fay', 'MK_REP', 20);
INSERT INTO `运算符` (`last_name`, `job_id`, `department_id`) VALUES ('Raphaely', 'PU_MAN', 30);
INSERT INTO `运算符` (`last_name`, `job_id`, `department_id`) VALUES ('Khoo', 'PU_CLERK', 30);
INSERT INTO `运算符` (`last_name`, `job_id`, `department_id`) VALUES ('Baida', 'PU_CLERK', 30);
INSERT INTO `运算符` (`last_name`, `job_id`, `department_id`) VALUES ('Tobias', 'PU_CLERK', 30);
INSERT INTO `运算符` (`last_name`, `job_id`, `department_id`) VALUES ('Himuro', 'PU_CLERK', 30);
INSERT INTO `运算符` (`last_name`, `job_id`, `department_id`) VALUES ('Colmenares', 'PU_CLERK', 30);
INSERT INTO `运算符` (`last_name`, `job_id`, `department_id`) VALUES ('Mavris', 'HR_REP', 40);
INSERT INTO `运算符` (`last_name`, `job_id`, `department_id`) VALUES ('Hunold', 'IT_PROG', 60);
INSERT INTO `运算符` (`last_name`, `job_id`, `department_id`) VALUES ('Ernst', 'IT_PROG', 60);
INSERT INTO `运算符` (`last_name`, `job_id`, `department_id`) VALUES ('Austin', 'IT_PROG', 60);
INSERT INTO `运算符` (`last_name`, `job_id`, `department_id`) VALUES ('Pataballa', 'IT_PROG', 60);
INSERT INTO `运算符` (`last_name`, `job_id`, `department_id`) VALUES ('Lorentz', 'IT_PROG', 60);
INSERT INTO `运算符` (`last_name`, `job_id`, `department_id`) VALUES ('Baer', 'PR_REP', 70);
INSERT INTO `运算符` (`last_name`, `job_id`, `department_id`) VALUES ('Greenberg', 'FI_MGR', 100);
INSERT INTO `运算符` (`last_name`, `job_id`, `department_id`) VALUES ('Faviet', 'FI_ACCOUNT', 100);
INSERT INTO `运算符` (`last_name`, `job_id`, `department_id`) VALUES ('Chen', 'FI_ACCOUNT', 100);
INSERT INTO `运算符` (`last_name`, `job_id`, `department_id`) VALUES ('Sciarra', 'FI_ACCOUNT', 100);
INSERT INTO `运算符` (`last_name`, `job_id`, `department_id`) VALUES ('Urman', 'FI_ACCOUNT', 100);
INSERT INTO `运算符` (`last_name`, `job_id`, `department_id`) VALUES ('Popp', 'FI_ACCOUNT', 100);
INSERT INTO `运算符` (`last_name`, `job_id`, `department_id`) VALUES ('Higgins', 'AC_MGR', 110);
INSERT INTO `运算符` (`last_name`, `job_id`, `department_id`) VALUES ('Gietz', 'AC_ACCOUNT', 110);
INSERT INTO `运算符` (`last_name`) VALUES ('Kochhar');
INSERT INTO `运算符` (`last_name`) VALUES ('Lorentz');
INSERT INTO `运算符` (`last_name`) VALUES ('Popp');
INSERT INTO `运算符` (`last_name`) VALUES ('Tobias');
INSERT INTO `运算符` (`last_name`) VALUES ('Colmenares');
INSERT INTO `运算符` (`last_name`) VALUES ('Vollman');
INSERT INTO `运算符` (`last_name`) VALUES ('Mourgos');
INSERT INTO `运算符` (`last_name`) VALUES ('Rogers');
INSERT INTO `运算符` (`last_name`) VALUES ('Doran');
INSERT INTO `运算符` (`last_name`) VALUES ('Fox');
INSERT INTO `运算符` (`last_name`) VALUES ('Johnson');
INSERT INTO `运算符` (`last_name`) VALUES ('Jones');
INSERT INTO `运算符` (`first_name`, `salary`) VALUES ('Steven', 24000.00);
INSERT INTO `运算符` (`first_name`, `salary`) VALUES ('Shelli', 2900.00);
INSERT INTO `运算符` (`first_name`, `salary`) VALUES ('Sigal', 2800.00);
INSERT INTO `运算符` (`first_name`, `salary`) VALUES ('Shanta', 6500.00);
INSERT INTO `运算符` (`first_name`, `salary`) VALUES ('Steven', 2200.00);
INSERT INTO `运算符` (`first_name`, `salary`) VALUES ('Stephen', 3200.00);
INSERT INTO `运算符` (`first_name`, `salary`) VALUES ('Sarath', 7000.00);
INSERT INTO `运算符` (`first_name`, `salary`) VALUES ('Sundar', 6400.00);
INSERT INTO `运算符` (`first_name`, `salary`) VALUES ('Sundita', 6100.00);
INSERT INTO `运算符` (`first_name`, `salary`) VALUES ('Sarah', 4000.00);
INSERT INTO `运算符` (`first_name`, `salary`) VALUES ('Samuel', 3200.00);
INSERT INTO `运算符` (`first_name`, `salary`) VALUES ('Susan', 6500.00);
INSERT INTO `运算符` (`first_name`, `salary`) VALUES ('Shelley', 12000.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Higgins', 'Accounting Manager', 12000.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Greenberg', 'Finance Manager', 12000.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Hartstein', 'Marketing Manager', 13000.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Raphaely', 'Purchasing Manager', 11000.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Russell', 'Sales Manager', 14000.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Partners', 'Sales Manager', 13500.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Errazuriz', 'Sales Manager', 12000.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Cambrault', 'Sales Manager', 11000.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Zlotkey', 'Sales Manager', 10500.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Higgins', 'Accounting Manager', 12000.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('King', 'President', 24000.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Kochhar', 'Administration Vice President', 17000.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('De Haan', 'Administration Vice President', 17000.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Greenberg', 'Finance Manager', 12000.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Mavris', 'Human Resources Representative', 6500.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Hartstein', 'Marketing Manager', 13000.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Baer', 'Public Relations Representative', 10000.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Raphaely', 'Purchasing Manager', 11000.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Russell', 'Sales Manager', 14000.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Partners', 'Sales Manager', 13500.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Errazuriz', 'Sales Manager', 12000.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Cambrault', 'Sales Manager', 11000.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Zlotkey', 'Sales Manager', 10500.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Tucker', 'Sales Representative', 10000.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('King', 'Sales Representative', 10000.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Vishney', 'Sales Representative', 10500.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Ozer', 'Sales Representative', 11500.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Bloom', 'Sales Representative', 10000.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Abel', 'Sales Representative', 11000.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Weiss', 'Stock Manager', 8000.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Fripp', 'Stock Manager', 8200.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Kaufling', 'Stock Manager', 7900.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Vollman', 'Stock Manager', 6500.00);
INSERT INTO `运算符` (`last_name`, `job_title`, `salary`) VALUES ('Mourgos', 'Stock Manager', 5800.00);
INSERT INTO `运算符` (`employee_id`, `employee_id & 1`) VALUES (100, 0);
INSERT INTO `运算符` (`employee_id`, `employee_id & 1`) VALUES (101, 1);
INSERT INTO `运算符` (`employee_id`, `employee_id & 1`) VALUES (102, 0);
INSERT INTO `运算符` (`employee_id`, `employee_id & 1`) VALUES (103, 1);
INSERT INTO `运算符` (`employee_id`, `employee_id & 1`) VALUES (104, 0);
INSERT INTO `运算符` (`last_name`, `年薪`) VALUES ('King', 288000.00);
INSERT INTO `运算符` (`last_name`, `年薪`) VALUES ('Kochhar', 204000.00);
INSERT INTO `运算符` (`last_name`, `年薪`) VALUES ('De Haan', 204000.00);
INSERT INTO `运算符` (`last_name`, `年薪`) VALUES ('King', 288000.00);
INSERT INTO `运算符` (`last_name`, `年薪`) VALUES ('Kochhar', 204000.00);
INSERT INTO `运算符` (`last_name`, `年薪`) VALUES ('De Haan', 204000.00);
